eBuy-elctronics/eBuy-elctronics/Controllers/CategoriesController.cs
using eBuy_elctronics_DB;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eBuy_elctronics.Controllers
{
    public class CategoriesController : Controller
    {
        #region EF Ref
        Entities DB = new Entities();
        #endregion

        #region Categories
        /// <summary>
        /// Get Selected Categories's list
        /// </summary>
        public ActionResult Index()
        {
            try
            {
                if (Session["user"] != null)
                {
                    IList<Category> _Category = DB.Categories.ToList();
                    return View(_Category);
                }
                else
                {
                    ViewBag.ErrorEx = "Session is expired.";
                    return View("Error");
                }
            }
            catch (Exception ex)
            {
                ViewBag.ErrorEx = ex.Message;
                return View("Error");
            }
        }
        #endregion

        #region Categories items
        /// <summary>
        /// Get selected all Categories items
        /// </summary>

        [HttpGet]
        public ActionResult CategoriesItems(int Id)
        {
            try
            {
                if (Session["user"] != null)
                {
                    IList<cGet_Items> _Get_Items = DB.sp_Get_Items().Where(x => x.CategoryID == Id).ToList();
                    ViewBag.count = _Get_Items.Count();
                    return View(_Get_Items);
                }
                else
                {
                    ViewBag.ErrorEx = "Session is expired.";
                    return View("Error");
                }
            }
            catch (Exception ex)
            {
                ViewBag.ErrorEx = ex.Message;
                return View("Error");
            }
        }
        #endregion
    }
}

eBuy-elctronics/eBuy-elctronics/Controllers/ItemsController.cs
using eBuy_elctronics_DB;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eBuy_elctronics.Controllers
{
    public class ItemsController : Controller
    {

        #region EF Ref
        Entities DB = new Entities();
        #endregion

        #region Get all items
        /// <summary>
        /// Get all items list to select the item and order or add to cart
        /// </summary>
        public ActionResult Index()
        {
            try
            {
                if (Session["user"] != null)
                {
                    IList<cGet_Items> _Get_Items = DB.sp_Get_Items().ToList();
                    ViewBag.count = _Get_Items.Count();
                    return View(_Get_Items);
                }
                else
                {
                    ViewBag.ErrorEx = "Session is expired.";
                    return View("Error");
                }
            }
            catch (Exception ex)
            {
                ViewBag.ErrorEx = ex.Message;
                return View("Error");
            }
        }
        #endregion

        #region Selected Item
        /// <summary>
        /// Get the selected item to order
        /// </summary>
        public ActionResult Display(int Id)
        {
            try
            {
                if (Session["user"] != null)
                {
                    cGet_Items _Get_Items = DB.sp_Get_Items().Where(x => x.ItemID == Id).FirstOrDefault();
                    return View(_Get_Items);
                }
                else
                {
                    ViewBag.ErrorEx = "Session is expired.";
                    return View("Error");
                }
            }
            catch (Exception ex)
            {
                ViewBag.ErrorEx = ex.Message;
                return View("Error");
            }
        }
        #endregion

        #region Check Quantity Availabilty
        /// <summary>
        /// Checking quantity availabilty to get result
        /// </summary>
        public JsonResult CheckQuantity(int ItemId, int Quantity, int InventoryId)
        {
            try
            {
                if (Session["user"] != null)
                {
                    var Check = DB.Inventories.Where(x => x.InventoryID == InventoryId && x.ItemID == ItemId).Select(x => x.Quantity).FirstOrDefault();
                    
                    if (Check > Quantity || Check == Quantity)
                    { Check = 1; }
                    else { Check = 0; }
                    return Json(Check, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    ViewBag.ErrorEx = "Session is expired.";
                    return Json(404, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                ViewBag.ErrorEx = ex.Message;
                return Json(404, JsonRequestBehavior.AllowGet);
            }
        }
        #endregion


    }
}

eBuy-elctronics/eBuy-elctronics/Views/Categories/CategoriesItems.cshtml
@model IEnumerable<eBuy_elctronics_DB.cGet_Items>
@{
    ViewBag.Title = "CategoriesItems";
    Layout = "~/Views/Shared/_CustomerLayout.cshtml";
    int Counter = 0;
}

<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">
                            <small>eBuy electronics</small>
                        </h1>
                    </div>
                </div>
                @foreach (var item in Model)
                {
                    Counter += 1;
                    if (Counter != 4)
                    {
                    <div class="row">
                        <div class="col-md-4 portfolio-item">
                            <a href="@Url.Action("Display", "Items", new { id = item.ItemID })">
                                <label>@item.ItemName</label>
                                <img class="img-responsive" src="@Url.Content("~/images/Items/" + item.ImageURL)">
                                <label>@item.ItemDesc</label><br />
                                Price: <b>@item.Price</b>
                            </a>
                        </div>
                    </div>
                    }
                    else
                    {
                        Counter = 0;
                    <br />
                    }
                }
            </div>
        </div>
    </div>
</div>
 <!-- Core Scripts - Include with every page -->
    <script src="@Url.Content("~/Content/bootstrap/js/jquery-1.10.2.js")"></script>

eBuy-elctronics/eBuy-elctronics/Views/Categories/Index.cshtml
@model IEnumerable<eBuy_elctronics_DB.Category>
@{
    ViewBag.Title = "eBuy Category";
    Layout = "~/Views/Shared/_CustomerLayout.cshtml";
   
}

<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <div class="container">

                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">
                            <small>eBuy electronics</small>
                        </h1>
                    </div>
                </div>
                @foreach (var item in Model)
                {
                   <div class="col-md-4 portfolio-item">
                        <a href="@Url.Action("CategoriesItems", "Categories", new { id = item.CategoryID })">
                            @if (item.CategoryImgUrl == null || item.CategoryImgUrl == "")
                            {
                                item.CategoryImgUrl = "no_image.jpg";
                            }
                            <img class="img-responsive" src="@Url.Content("~/images/CategoryLogos/" + item.CategoryImgUrl)" style="width:300px; height:200px;">
                        </a>
                        <label>@item.CategoryName</label>
                    </div>
                }
            </div>
        </div>
    </div>
</div>
 <!-- Core Scripts - Include with every page -->
    <script src="@Url.Content("~/Content/bootstrap/js/jquery-1.10.2.js")"></script>