eBuy-elctronics/eBuy-elctronics/Controllers/ChangePasswordController.cs
using eBuy_elctronics_DB;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using eBuy_elctronics.Models;


namespace eBuy_elctronics.Controllers
{
    public class ChangePasswordController : Controller
    {
        #region EF Ref
        Entities DB = new Entities();
        #endregion

        #region change password details
        public ActionResult Index()
        {
            try
            {
                if (Session["user"] != null) 
                {
                    return View();
                }
                else
                {
                    ViewBag.ErrorEx = "Session is expired.";
                    return View("Error");
                }
            }
            catch (Exception ex)
            {
                ViewBag.ErrorEx = ex.Message;
                return View("Index");
            }
        }
        #endregion

        #region add new password
        /// <summary>
        /// Add new password required old password and login name
        /// </summary>
        public ActionResult addnewpassword(ChangePasword obj)
        {
            try
            {
                if (Session["user"] != null)
                {
                    Logindetail user = DB.Logindetails.Where(x => x.Loginname == obj.username && x.Password == obj.oldpassword && x.IsActive == true && x.IsDeleted == false).FirstOrDefault();
                    if (user != null)
                    {
                        user.Password = obj.newpassword;
                        user.Passmodifieddate = DateTime.Now;
                        user.UpdatedBy = user.Loginid.ToString();
                        user.UpdatedDate = DateTime.Now;
                        
                        DB.SaveChanges();
                        ViewBag.sucMsg = "Password is changed successfully.";
                        return View("Index");
                    }
                    else
                    {
                        ViewBag.sucMsg = "Login name and password is not matched please try agin.";
                        return View("Index");
                    }
                    
                }
                else
                {
                    ViewBag.ErrorEx = "Session is expired.";
                    return View("Error");
                }
            }
            catch (Exception ex)
            {
                ViewBag.ErrorEx = ex.Message;
                return View("Index");
            }
        }
        #endregion
    }
}

eBuy-elctronics/eBuy-elctronics/Views/ChangePassword/Index.cshtml
@model eBuy_elctronics_DB.Logindetail
@{
    ViewBag.Title = "Change Password";
    Layout = "~/Views/Shared/_CustomerLayout.cshtml";
}


<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-6">
            <h1>Change Password</h1>
            <span class="style5">@ViewBag.sucMsg</span>

            @using (Html.BeginForm("addnewpassword", "ChangePassword", FormMethod.Post, new { role = "form" }))
            {
                <div class="form-group">
                    <label>User Name</label>
                    <input class="form-control" type="text" name="username" placeholder="Login name is reuired" />
                </div>
                <div class="form-group">
                    <label>Old Password</label>
                    <input class="form-control" type="password" name="oldpassword" placeholder="Password is required" />
                </div>
                <div class="form-group">
                    <label>New Password</label>
                    <input class="form-control" type="password" name="newpassword" placeholder="Password is required" />
                </div>
                <input type="submit" name="Submit" value="Change" class="btn btn-success" />
                <input type="reset" name="Submit2" value="Reset" class="btn ntn-primary" />
            }
        </div>
    </div>
</div>