eBuy-elctronics/eBuy-elctronics/Controllers/FeedBackController.cs
using eBuy_elctronics_DB;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eBuy_elctronics.Controllers
{
    public class FeedBackController : Controller
    {
        #region EF Ref
        Entities DB = new Entities();
        #endregion

        #region Feedback
        /// <summary>
        /// Add FeedBack to products
        /// </summary>
        public ActionResult Index()
        {
            try
            {
                if (Session["user"] != null)
                {
                    Logindetail user = Session["user"] as Logindetail;
                    LoadDDL();
                    return View();
                }
                else
                {
                    ViewBag.ErrorEx = "Session is expired.";
                    return View("Error");
                }
            }
            catch (Exception ex)
            {
                ViewBag.ErrorEx = ex.Message;
                return View("Index");
            }
        }
        #endregion

        #region Create Feedback
        /// <summary>
        /// Create FeedBack 
        /// </summary>
        public ActionResult Create(FeedbackDesc obj)
        {
            try
            {

                if (Session["user"] != null)
                {
                    Logindetail user = Session["user"] as Logindetail;
                    obj.LoginID = user.Loginid;
                    obj.CreatedBy = user.Loginid.ToString();
                    obj.CreatedDate = DateTime.Now;
                    obj.IsDeleted = false;
                    obj.IsActive = true;
                    DB.FeedbackDescs.Add(obj);
                    DB.SaveChanges();
                    LoadDDL();
                    ViewBag.sucMsg = "Feedback sends success.";
                    return View("Index");
                }
                else
                {
                    ViewBag.ErrorEx = "Session is expired.";
                    return View("Error");
                }
            }
            catch (Exception ex)
            {
                ViewBag.ErrorEx = ex.Message;
                return View("Index");
            }
        }
        #endregion

        #region DDL
        /// <summary>
        /// Load the brands and category to bind the data to drop down list
        /// </summary>
        public void LoadDDL()
        {
            var Category = DB.Categories.ToList();
            ViewBag.CategoryId = new SelectList(Category, "CategoryID", "CategoryName");


            var brands = DB.Brands.ToList();
            ViewBag.BrandId = new SelectList(brands, "BrandID", "BrandName");

            var item = DB.Items.ToList();
            ViewBag.ItemId = new SelectList(item, "ItemID", "ItemName");
        }
        #endregion
    }
}

eBuy-elctronics/eBuy-elctronics/Views/FeedBack/Index.cshtml
@model IEnumerable<eBuy_elctronics_DB.FeedbackDesc>
@{
    ViewBag.Title = "eBuy Feedback";
    Layout = "~/Views/Shared/_CustomerLayout.cshtml";
   // Layout = null;
}

<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Create-FeedBack</h1>
            <span class="text-success">@ViewBag.sucMsg</span>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    @Html.ActionLink("Back to Home", "Index", "Home")
                </div>
                <div class="panel-body">
                    <div class="row">
                        
                        <div class="col-lg-6">
                            
                            @using (Html.BeginForm("Create", "FeedBack", FormMethod.Post, new {id = "feedbackvalid" }))
                            {
                                
                                <div class="form-group">
                                    <label>Brand</label>
                                    @Html.DropDownList("BrandId", @ViewBag.BrandId as SelectList,"--Select Brand--", new {@class="form-control" })
                                </div>
                                <div class="form-group">
                                    <label>Category</label>
                                     @Html.DropDownList("CategoryId", @ViewBag.CategoryId as SelectList,"--Select Category--", new {@class="form-control" })
                                </div>
                                <div class="form-group">
                                    <label>Item</label>
                                     @Html.DropDownList("ItemId", @ViewBag.ItemId as SelectList,"--Select Item--", new {@class="form-control" })
                                </div>
                                <div class="form-group">
                                    <label>FeedBack Description</label>
                                    <textarea class="form-control" placeholder="Enter item description" cols="2" name="Feedbackdesc1"></textarea>
                                </div>
                                <div class="form-group">
                                    <input name="Input" type="submit" value="Submit" class="btn btn-success" />
                                    <input name="Input" type="reset" value="Reset" class="btn btn-default" />
                                </div>

                            }
                        </div>
                    </div>
                </div>

                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
</div>

<script src="@Url.Content("~/Scripts/jquery-1.7.1.js")"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.js")"></script>
<script src="@Url.Content("~/Scripts/jquery-form-validation-V.1.js")"></script>