eBuy-elctronics/eBuy-elctronics/Controllers/CartController.cs
using eBuy_elctronics_DB;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eBuy_elctronics.Controllers
{
    public class CartController : Controller
    {
        #region EF Ref
        Entities DB = new Entities();
        #endregion

        #region Cart list
        /// <summary>
        /// Get all stored cart list
        /// </summary>
        public ActionResult Index()
        {
            try
            {
                if (Session["user"] != null)
                {
                    Logindetail LogInfo = Session["user"] as Logindetail;
                    IList<cGet_AllCart> _AllCart = DB.sp_Get_AllCart(LogInfo.Loginid).ToList();
                    ViewBag.Count = _AllCart.Count();
                    return View(_AllCart);
                }
                else
                {
                    ViewBag.ErrorEx = "Session is expired.";
                    return View("Error");
                }
            }
            catch (Exception ex)
            {
                ViewBag.ErrorEx = ex.Message;
                return View("Index");
            }
        }
        #endregion

    }
}

eBuy-elctronics/eBuy-elctronics/Controllers/ItemsController.cs
using eBuy_elctronics_DB;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eBuy_elctronics.Controllers
{
    public class ItemsController : Controller
    {

        #region EF Ref
        Entities DB = new Entities();
        #endregion

        #region Get all items
        /// <summary>
        /// Get all items list to select the item and order or add to cart
        /// </summary>
        public ActionResult Index()
        {
            try
            {
                if (Session["user"] != null)
                {
                    IList<cGet_Items> _Get_Items = DB.sp_Get_Items().ToList();
                    ViewBag.count = _Get_Items.Count();
                    return View(_Get_Items);
                }
                else
                {
                    ViewBag.ErrorEx = "Session is expired.";
                    return View("Error");
                }
            }
            catch (Exception ex)
            {
                ViewBag.ErrorEx = ex.Message;
                return View("Error");
            }
        }
        #endregion

        #region Selected Item
        /// <summary>
        /// Get the selected item to order
        /// </summary>
        public ActionResult Display(int Id)
        {
            try
            {
                if (Session["user"] != null)
                {
                    cGet_Items _Get_Items = DB.sp_Get_Items().Where(x => x.ItemID == Id).FirstOrDefault();
                    return View(_Get_Items);
                }
                else
                {
                    ViewBag.ErrorEx = "Session is expired.";
                    return View("Error");
                }
            }
            catch (Exception ex)
            {
                ViewBag.ErrorEx = ex.Message;
                return View("Error");
            }
        }
        #endregion

        #region Check Quantity Availabilty
        /// <summary>
        /// Checking quantity availabilty to get result
        /// </summary>
        public JsonResult CheckQuantity(int ItemId, int Quantity, int InventoryId)
        {
            try
            {
                if (Session["user"] != null)
                {
                    var Check = DB.Inventories.Where(x => x.InventoryID == InventoryId && x.ItemID == ItemId).Select(x => x.Quantity).FirstOrDefault();
                    
                    if (Check > Quantity || Check == Quantity)
                    { Check = 1; }
                    else { Check = 0; }
                    return Json(Check, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    ViewBag.ErrorEx = "Session is expired.";
                    return Json(404, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                ViewBag.ErrorEx = ex.Message;
                return Json(404, JsonRequestBehavior.AllowGet);
            }
        }
        #endregion


    }
}

eBuy-elctronics/eBuy-elctronics/Controllers/LoginController.cs
using eBuy_elctronics_DB;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace eBuy_elctronics.Controllers
{
    [AllowAnonymous]
    public class LoginController : Controller
    {
        #region EF Ref
        Entities DB = new Entities();
        #endregion

        #region Login
        /// <summary>
        /// Get Login details
        /// </summary>
        public ActionResult Index(string msg)
        {
            // checking retuned url
            if (!string.IsNullOrEmpty(msg))
                ViewBag.sucMsg = msg;

            return View();
        }
        #endregion

        #region Check login access
        /// <summary>
        /// Get valid login details
        /// </summary>
        public ActionResult CheckLoginAccess(Logindetail Lobj, string ReturnUrl)
        {
            try
            {
                // Checking user exist or given user name and password
                Logindetail _User = DB.Logindetails.Where(x => x.Loginname == Lobj.Loginname && x.Password == Lobj.Password && x.IsDeleted == false).FirstOrDefault();
                // Validating user 
                if (_User != null)
                {
                    //Seting form authentication
                    FormsAuthentication.SetAuthCookie(_User.Logintype, false);
                                                            
                    //Store the user information in session
                    Session["user"] = _User as Logindetail;

                    //Checking user role accessing the controller's
                    if (_User.Logintype == "Admin")
                        return RedirectToAction("Index", "cmsAdmin");
                    else if (_User.Logintype == "Customer")
                        return RedirectToAction("Index", "Home");
                }
                    //In valid user
                else
                    ViewBag.sucMsg = "user name and password incorrect.";
                return View("Index");
            }
            catch (Exception ex)
            {
                // system handle exception return error view page.
                ViewBag.exError = ex.Message;
                return View("Error");
            }
        }
        #endregion

        #region Log out
        /// <summary>
        /// Log off customer details safe
        /// </summary>
        public ActionResult LogOff()
        {
            //remove the authenticated user
            FormsAuthentication.SignOut();
            //Remove store information in sessions
            Session.Abandon();
            Session["user"] = null;
            ViewBag.sucMsg = "Successfully sign off.";
            return View("Index");
        }
        #endregion
    }
}

eBuy-elctronics/eBuy-elctronics/Controllers/OrderController.cs
using eBuy_elctronics_DB;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eBuy_elctronics.Controllers
{
    public class OrderController : Controller
    {
        #region EF Ref
        Entities DB = new Entities();
        #endregion

        #region Orders list
        /// <summary>
        /// Get all orders to check ordered list
        /// </summary>
        public ActionResult Index()
        {
            try
            {
                if (Session["user"] != null)
                {
                    Logindetail LogInfo = Session["user"] as Logindetail;
                    IList<cGet_AllOrders> _AllOrders = DB.sp_Get_AllOrders(LogInfo.Loginid).ToList();
                    return View(_AllOrders);
                }
                else
                {
                    ViewBag.ErrorEx = "Session is expired.";
                    return View("Error");
                }
            }
            catch (Exception ex)
            {
                ViewBag.ErrorEx = ex.Message;
                return View("Index");
            }
        }
        #endregion

        #region Add Orders
        /// <summary>
        /// Add Orders to place the ordered product
        /// </summary>
        public ActionResult AddOrder(int Id)
        {
            try
            {
                if (Session["user"] != null)
                {
                   // Logindetail LogInfo = Session["user"] as Logindetail;
                   // DB.sp_Save_Orders(Id, 5, LogInfo.Loginid);
                    ViewBag.sucMsg = "Added new order success.";
                    return View("Index");
                }
                else
                {
                    ViewBag.ErrorEx = "Session is expired.";
                    return View("Error");
                }
            }
            catch (Exception ex)
            {
                ViewBag.ErrorEx = ex.Message;
                return View("Index");
            }
        }
        #endregion

        #region Add Cart
        /// <summary>
        /// Add Cart to store selected product
        /// </summary>
        public ActionResult AddCart(int Id)
        {
            try
            {
                if (Session["user"] != null)
                {
                    Logindetail LogInfo = Session["user"] as Logindetail;

                    DB.sp_SaveCart(Id, 0, 0, LogInfo.Loginid);

                    ViewBag.sucMsg = "Added new cart success.";
                    return View("Index");
                }
                else
                {
                    ViewBag.ErrorEx = "Session is expired.";
                    return View("Error");
                }
            }
            catch (Exception ex)
            {
                ViewBag.ErrorEx = ex.Message;
                return View("Index");
            }
        }
        #endregion

    }
}

eBuy-elctronics/eBuy-elctronics/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>@ViewBag.title</title>

    <!-- Core CSS - Include with every page -->
    <link href="@Url.Content("~/Content/bootstrap/css/bootstrap.min.css")" rel="stylesheet">
    <link href="@Url.Content("~/Content/bootstrap/font-awesome/css/font-awesome.css")" rel="stylesheet">

    <!-- Page-Level Plugin CSS - Tables -->
    <link href="@Url.Content("~/Content/bootstrap/css/plugins/dataTables/dataTables.bootstrap.css")" rel="stylesheet">

    <!-- SB Admin CSS - Include with every page -->
    <link href="@Url.Content("~/Content/bootstrap/css/sb-admin.css")" rel="stylesheet">
</head>

<body>

    <div id="wrapper">

        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="@Url.Action("Index", "cmsAdmin")">Admin v1.0</a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">
              
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i><i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        @*<li><a href="@Url.Action("Index", "MyProfile")"><i class="fa fa-user fa-fw"></i>User Profile</a>
                        </li>*@
                        <li><a href="@Url.Action("Index", "ChangePassword")"><i class="fa fa-gear fa-fw"></i>Change Password</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="@Url.Action("LogOff", "Login")"><i class="fa fa-sign-out fa-fw"></i>Logout</a>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->

        </nav>
        <!-- /.navbar-static-top -->

       
        <nav class="navbar-default navbar-static-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav" id="side-menu">

                    <li>
                        <a href="@Url.Action("Index", "cmsAdmin")"><i class="fa fa-dashboard fa-fw"></i>Dashboard</a>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i>Products<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a href="@Url.Action("Index", "cmsBrands")">Brands</a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index", "cmsCategories")">Category</a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index", "cmsItems")">Items</a>
                            </li>
                        </ul>
                        <!-- /.nav-second-level -->
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-sitemap fa-fw"></i>Inventory<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a href="@Url.Action("Index", "cmsInventories")">All Inventories</a>
                            </li>
                        </ul>
                        <!-- /.nav-second-level -->
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-envelope fa-fw"></i>Customer Queries<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a href="@Url.Action("Index", "cmsQueries")">Queries</a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index", "cmsFeedBack")">FeedBack</a>
                            </li>                           
                        </ul>
                        <!-- /.nav-second-level -->
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-table fa-fw"></i>Sales<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a href="@Url.Action("Index", "cmsOrders")"><i class="fa fa-files-o fa-fw"></i>Orders</a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index", "cmsDateWiseOrders")"><i class="fa fa-files-o fa-fw"></i>Date Wise Orders</a>
                            </li>
                           @* <li>
                                <a href="@Url.Action("Index", "cmsSalesReport")"><i class="fa fa-files-o fa-fw"></i>Sales Report</a>
                            </li>*@
                        </ul>
                        <!-- /.nav-second-level -->
                    </li>

                    </ul>
                    <!-- /#side-menu -->
            </div>

            <!-- /.sidebar-collapse -->
        </nav>
        <!-- /.navbar-static-side -->
        @RenderBody()
    </div>
    <!-- /#page-wrapper -->

    <!-- Core Scripts - Include with every page -->
  @*  <script src="@Url.Content("~/Content/bootstrap/js/jquery-1.10.2.js")"></script>*@
    <script src="@Url.Content("~/Content/bootstrap/js/bootstrap.min.js")"></script>
    <script src="@Url.Content("~/Content/bootstrap/js/plugins/metisMenu/jquery.metisMenu.js")"></script>

    <!-- Page-Level Plugin Scripts - Tables -->
    <script src="@Url.Content("~/Content/bootstrap/js/plugins/dataTables/jquery.dataTables.js")"></script>
    <script src="@Url.Content("~/Content/bootstrap/js/plugins/dataTables/dataTables.bootstrap.js")"></script>

    <!-- SB Admin Scripts - Include with every page -->
    <script src="@Url.Content("~/Content/bootstrap/js/sb-admin.js")"></script>

    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>
        $(document).ready(function () {
            $('#dataTables-example').dataTable();
        });
    </script>
    <style>
        form label.error {
        font: 10px Tahoma,sans-serif;
        color: #ED7476;
        margin-left: 5px;
    }

    form input.error, form input.error:hover, form input.error:focus, form select.error,
    form textarea.error {
        border: 1px solid #ED7476;
        background: #FFEDED;
    }
    </style>

</body>
</html>

eBuy-elctronics/eBuy-elctronics/Views/Shared/_CustomerLayout.cshtml
<!DOCTYPE html>
@using eBuy_elctronics_DB;
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>@ViewBag.title</title>

    <!-- Core CSS - Include with every page -->
    <link href="@Url.Content("~/Content/bootstrap/css/bootstrap.min.css")" rel="stylesheet">
    <link href="@Url.Content("~/Content/bootstrap/font-awesome/css/font-awesome.css")" rel="stylesheet">

    <!-- Page-Level Plugin CSS - Tables -->
    <link href="@Url.Content("~/Content/bootstrap/css/plugins/dataTables/dataTables.bootstrap.css")" rel="stylesheet">

    <!-- SB Admin CSS - Include with every page -->
    <link href="@Url.Content("~/Content/bootstrap/css/sb-admin.css")" rel="stylesheet">
  
</head>

<body>

    <div id="wrapper">

        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="@Url.Action("Index", "Home")">eBuy electronics</a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">
              
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i><i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                       @* <li><a href="@Url.Action("Index", "MyProfile")"><i class="fa fa-user fa-fw"></i>User Profile</a>
                        </li>*@
                        <li><a href="@Url.Action("Index", "ChangePassword")"><i class="fa fa-gear fa-fw"></i>Change Password</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="@Url.Action("LogOff", "Login")"><i class="fa fa-sign-out fa-fw"></i>Logout</a>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->

        </nav>
        <!-- /.navbar-static-top -->

        <nav class="navbar-default navbar-static-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav" id="side-menu">

                    <li>
                        <a href="@Url.Action("Index", "Home")"><i class="fa fa-dashboard fa-fw"></i>Home</a>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i>Products<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a href="@Url.Action("Index", "Brands")">Brands</a>                               
                            </li>
                            <li>
                                <a href="@Url.Action("Index", "Categories")">Category</a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index", "Items")">Items</a>
                            </li>
                        </ul>
                        <!-- /.nav-second-level -->
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i>Buy<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a href="@Url.Action("Index", "Search")">Search</a>
                            </li>
                        </ul>
                        <!-- /.nav-second-level -->
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-edit fa-fw"></i>Queries<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a href="@Url.Action("Index","Queries")">View Reponse</a>
                            </li>
                            <li>
                                <a href="@Url.Action("CreateQuery","Queries")">Send Query</a>
                            </li>


                        </ul>
                        <!-- /.nav-second-level -->
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "Cart")"><i class="fa fa-table fa-fw"></i>View Cart</a>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i>Orders<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a href="@Url.Action("Index", "Order")">All orders</a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index", "OrdersByDate")">View by date</a>
                            </li>
                        </ul>
                        <!-- /.nav-second-level -->
                        
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "FeedBack")"><i class="fa fa-edit fa-fw"></i>FeedBack</a>
                    </li>
                </ul>
                <!-- /#side-menu -->
            </div>

            <!-- /.sidebar-collapse -->
        </nav>

        <!-- /.navbar-static-side -->
        @RenderBody()
    </div>
    <!-- /#page-wrapper -->

   
     <!-- Page-Level Plugin Scripts - Tables -->
    <script src="@Url.Content("~/Content/bootstrap/js/plugins/dataTables/jquery.dataTables.js")"></script>
    <script src="@Url.Content("~/Content/bootstrap/js/plugins/dataTables/dataTables.bootstrap.js")"></script>

    <script src="@Url.Content("~/Content/bootstrap/js/bootstrap.min.js")"></script>
    <script src="@Url.Content("~/Content/bootstrap/js/plugins/metisMenu/jquery.metisMenu.js")"></script>

   

    <!-- SB Admin Scripts - Include with every page -->
    <script src="@Url.Content("~/Content/bootstrap/js/sb-admin.js")"></script>

    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>
        $(document).ready(function () {
            $('#dataTables-example').dataTable();
            $('#dataTables-example1').dataTable();
        });
    </script>
    <style>
        form label.error {
        font: 10px Tahoma,sans-serif;
        color: #ED7476;
        margin-left: 5px;
    }

    form input.error, form input.error:hover, form input.error:focus, form select.error,
    form textarea.error {
        border: 1px solid #ED7476;
        background: #FFEDED;
    }
    </style>
</body>
</html>